### ISSUE TITLE
Regression Compilation broken

### ISSUE THREAD

**Issue by vladisslav2011** [gqrx-sdr/gqrx#1091]
Compilation is broken on my 'weak' test system (Atom N270) since https://github.com/gqrx-sdr/gqrx/pull/1088/commits/5e923578e7f50cfca36f1ede42d12f745a07ea27

Steps to reproduce:
1. Checkout master
2. Configure and make

Expected results:
gqrx builds and runs

Observed results:
```
make -j36
[  1%] Automatic moc for target gqrx
[  1%] Built target gqrx_automoc
[  2%] Building CXX object src/CMakeFiles/gqrx.dir/applications/gqrx/remote_control.cpp.o
/home/vlad/gqrx-my/src/applications/gqrx/remote_control.cpp: In member function 'void RemoteControl::acceptConnection()':
/home/vlad/gqrx-my/src/applications/gqrx/remote_control.cpp:174:21: error: 'class QHostAddress' has no member named 'isEqual'
         if (address.isEqual(QHostAddress(allowed_host)))
                     ^
src/CMakeFiles/gqrx.dir/build.make:255: recipe for target 'src/CMakeFiles/gqrx.dir/applications/gqrx/remote_control.cpp.o' failed
make[2]: *** [src/CMakeFiles/gqrx.dir/applications/gqrx/remote_control.cpp.o] Error 1
CMakeFiles/Makefile2:135: recipe for target 'src/CMakeFiles/gqrx.dir/all' failed
make[1]: *** [src/CMakeFiles/gqrx.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

Conditions:
```
dpkg -l |grep qt5
ii  libqt5concurrent5:i386                5.5.1+dfsg-16ubuntu7.7                   i386         Qt 5 concurrent module
ii  libqt5core5a:i386                     5.5.1+dfsg-16ubuntu7.7                   i386         Qt 5 core module
ii  libqt5dbus5:i386                      5.5.1+dfsg-16ubuntu7.7                   i386         Qt 5 D-Bus module
ii  libqt5gui5:i386                       5.5.1+dfsg-16ubuntu7.7                   i386         Qt 5 GUI module
ii  libqt5network5:i386                   5.5.1+dfsg-16ubuntu7.7                   i386         Qt 5 network module
ii  libqt5printsupport5:i386              5.5.1+dfsg-16ubuntu7.7                   i386         Qt 5 print support module
ii  libqt5sql5:i386                       5.5.1+dfsg-16ubuntu7.7                   i386         Qt 5 SQL module
ii  libqt5svg5:i386                       5.5.1-2build1                            i386         Qt 5 SVG module
ii  libqt5svg5-dev:i386                   5.5.1-2build1                            i386         Qt 5 SVG module development files
ii  libqt5test5:i386                      5.5.1+dfsg-16ubuntu7.7                   i386         Qt 5 test module
ii  libqt5widgets5:i386                   5.5.1+dfsg-16ubuntu7.7                   i386         Qt 5 widgets module
ii  libqt5xml5:i386                       5.5.1+dfsg-16ubuntu7.7                   i386         Qt 5 XML module
ii  qt5-qmake:i386                        5.5.1+dfsg-16ubuntu7.7                   i386         Qt 5 qmake Makefile generator tool
```

I suggest using https://doc.qt.io/qt-5/qhostaddress.html#operator-eq-eq instead of `isEqual`.

**Comment by argilo** [comment]
Gqrx dropped support for Ubuntu 16.04 almost a year ago, because it is an obsolete release: https://github.com/gqrx-sdr/gqrx/commit/867746ddfdb30c1da9c0b7eb9e662063a138422f

I don't see any point in continuing to support it.
